// <auto-generated />
using System;
using JKalixto_System.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JKalixto_System.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260918004142_AgregaHistorialLimpieza")]
    partial class AgregaHistorialLimpieza
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("JKalixto_System.Domain.Models.Acompanante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstadiaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EstadiaId");

                    b.ToTable("Acompanantes", (string)null);
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.AcompananteReserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReservaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReservaId");

                    b.ToTable("AcompanantesReserva", (string)null);
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.CierreCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalHotel")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalSauna")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Turno")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CierresCaja", (string)null);
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.ClienteSauna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsHuespedHotel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EstadiaHotelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroCandado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("RUC")
                        .HasColumnType("TEXT");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("TEXT");

                    b.Property<int>("Seccion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoComprobante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EstadiaHotelId");

                    b.ToTable("ClientesSauna", (string)null);
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("VentaSaunaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaSaunaId");

                    b.ToTable("DetallesVenta", (string)null);
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.Estadia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AccesoSaunaIncluido")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoFacturacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCheckIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaCheckOut")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("HabitacionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LugarResidencia")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MetodoPago")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MotivoViaje")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroComprobante")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.Property<string>("RUC")
                        .HasColumnType("TEXT");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Sexo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoComprobante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAcumulado")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioCheckInId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsuarioCheckOutId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HabitacionId");

                    b.HasIndex("UsuarioCheckInId");

                    b.HasIndex("UsuarioCheckOutId");

                    b.ToTable("Estadias", (string)null);
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.Habitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacidadMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaInicioMantenimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoMantenimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Piso")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TarifaNoche")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Habitaciones", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacidadMax = 1,
                            Estado = 0,
                            Numero = 101,
                            Piso = 1,
                            TarifaNoche = 120m,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 2,
                            CapacidadMax = 2,
                            Estado = 0,
                            Numero = 102,
                            Piso = 1,
                            TarifaNoche = 150m,
                            Tipo = 1
                        },
                        new
                        {
                            Id = 3,
                            CapacidadMax = 2,
                            Estado = 0,
                            Numero = 103,
                            Piso = 1,
                            TarifaNoche = 150m,
                            Tipo = 2
                        },
                        new
                        {
                            Id = 4,
                            CapacidadMax = 4,
                            Estado = 0,
                            Numero = 104,
                            Piso = 1,
                            TarifaNoche = 190m,
                            Tipo = 3
                        },
                        new
                        {
                            Id = 5,
                            CapacidadMax = 1,
                            Estado = 0,
                            Numero = 105,
                            Piso = 1,
                            TarifaNoche = 120m,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 6,
                            CapacidadMax = 2,
                            Estado = 0,
                            Numero = 106,
                            Piso = 1,
                            TarifaNoche = 150m,
                            Tipo = 1
                        },
                        new
                        {
                            Id = 7,
                            CapacidadMax = 2,
                            Estado = 0,
                            Numero = 107,
                            Piso = 1,
                            TarifaNoche = 150m,
                            Tipo = 2
                        },
                        new
                        {
                            Id = 8,
                            CapacidadMax = 4,
                            Estado = 0,
                            Numero = 108,
                            Piso = 1,
                            TarifaNoche = 190m,
                            Tipo = 3
                        },
                        new
                        {
                            Id = 9,
                            CapacidadMax = 1,
                            Estado = 0,
                            Numero = 109,
                            Piso = 1,
                            TarifaNoche = 120m,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 10,
                            CapacidadMax = 1,
                            Estado = 0,
                            Numero = 201,
                            Piso = 2,
                            TarifaNoche = 120m,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 11,
                            CapacidadMax = 2,
                            Estado = 0,
                            Numero = 202,
                            Piso = 2,
                            TarifaNoche = 150m,
                            Tipo = 1
                        },
                        new
                        {
                            Id = 12,
                            CapacidadMax = 2,
                            Estado = 0,
                            Numero = 203,
                            Piso = 2,
                            TarifaNoche = 150m,
                            Tipo = 2
                        },
                        new
                        {
                            Id = 13,
                            CapacidadMax = 4,
                            Estado = 0,
                            Numero = 204,
                            Piso = 2,
                            TarifaNoche = 190m,
                            Tipo = 3
                        },
                        new
                        {
                            Id = 14,
                            CapacidadMax = 1,
                            Estado = 0,
                            Numero = 205,
                            Piso = 2,
                            TarifaNoche = 120m,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 15,
                            CapacidadMax = 2,
                            Estado = 0,
                            Numero = 206,
                            Piso = 2,
                            TarifaNoche = 150m,
                            Tipo = 1
                        },
                        new
                        {
                            Id = 16,
                            CapacidadMax = 2,
                            Estado = 0,
                            Numero = 207,
                            Piso = 2,
                            TarifaNoche = 150m,
                            Tipo = 2
                        },
                        new
                        {
                            Id = 17,
                            CapacidadMax = 4,
                            Estado = 0,
                            Numero = 208,
                            Piso = 2,
                            TarifaNoche = 190m,
                            Tipo = 3
                        },
                        new
                        {
                            Id = 18,
                            CapacidadMax = 1,
                            Estado = 0,
                            Numero = 209,
                            Piso = 2,
                            TarifaNoche = 120m,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 19,
                            CapacidadMax = 1,
                            Estado = 0,
                            Numero = 301,
                            Piso = 3,
                            TarifaNoche = 120m,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 20,
                            CapacidadMax = 2,
                            Estado = 0,
                            Numero = 302,
                            Piso = 3,
                            TarifaNoche = 150m,
                            Tipo = 1
                        },
                        new
                        {
                            Id = 21,
                            CapacidadMax = 2,
                            Estado = 0,
                            Numero = 303,
                            Piso = 3,
                            TarifaNoche = 150m,
                            Tipo = 2
                        },
                        new
                        {
                            Id = 22,
                            CapacidadMax = 4,
                            Estado = 0,
                            Numero = 304,
                            Piso = 3,
                            TarifaNoche = 190m,
                            Tipo = 3
                        },
                        new
                        {
                            Id = 23,
                            CapacidadMax = 1,
                            Estado = 0,
                            Numero = 305,
                            Piso = 3,
                            TarifaNoche = 120m,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 24,
                            CapacidadMax = 2,
                            Estado = 0,
                            Numero = 306,
                            Piso = 3,
                            TarifaNoche = 150m,
                            Tipo = 1
                        },
                        new
                        {
                            Id = 25,
                            CapacidadMax = 2,
                            Estado = 0,
                            Numero = 307,
                            Piso = 3,
                            TarifaNoche = 150m,
                            Tipo = 2
                        },
                        new
                        {
                            Id = 26,
                            CapacidadMax = 4,
                            Estado = 0,
                            Numero = 308,
                            Piso = 3,
                            TarifaNoche = 190m,
                            Tipo = 3
                        },
                        new
                        {
                            Id = 27,
                            CapacidadMax = 1,
                            Estado = 0,
                            Numero = 309,
                            Piso = 3,
                            TarifaNoche = 120m,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 28,
                            CapacidadMax = 1,
                            Estado = 0,
                            Numero = 401,
                            Piso = 4,
                            TarifaNoche = 120m,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 29,
                            CapacidadMax = 2,
                            Estado = 0,
                            Numero = 402,
                            Piso = 4,
                            TarifaNoche = 150m,
                            Tipo = 1
                        },
                        new
                        {
                            Id = 30,
                            CapacidadMax = 2,
                            Estado = 0,
                            Numero = 403,
                            Piso = 4,
                            TarifaNoche = 150m,
                            Tipo = 2
                        },
                        new
                        {
                            Id = 31,
                            CapacidadMax = 4,
                            Estado = 0,
                            Numero = 404,
                            Piso = 4,
                            TarifaNoche = 190m,
                            Tipo = 3
                        },
                        new
                        {
                            Id = 32,
                            CapacidadMax = 1,
                            Estado = 0,
                            Numero = 405,
                            Piso = 4,
                            TarifaNoche = 120m,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 33,
                            CapacidadMax = 2,
                            Estado = 0,
                            Numero = 406,
                            Piso = 4,
                            TarifaNoche = 150m,
                            Tipo = 1
                        },
                        new
                        {
                            Id = 34,
                            CapacidadMax = 2,
                            Estado = 0,
                            Numero = 407,
                            Piso = 4,
                            TarifaNoche = 150m,
                            Tipo = 2
                        },
                        new
                        {
                            Id = 35,
                            CapacidadMax = 2,
                            Estado = 0,
                            Numero = 408,
                            Piso = 4,
                            TarifaNoche = 250m,
                            Tipo = 4
                        },
                        new
                        {
                            Id = 36,
                            CapacidadMax = 2,
                            Estado = 0,
                            Numero = 409,
                            Piso = 4,
                            TarifaNoche = 250m,
                            Tipo = 4
                        });
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.Insumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Categoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockActual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Insumos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Categoria = 0,
                            Nombre = "Frazada de alpaca (antialérgica)",
                            StockActual = 40,
                            StockMinimo = 10,
                            UnidadMedida = "unidad"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Categoria = 0,
                            Nombre = "Frazada común",
                            StockActual = 60,
                            StockMinimo = 15,
                            UnidadMedida = "unidad"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Categoria = 0,
                            Nombre = "Cobertor de cama",
                            StockActual = 50,
                            StockMinimo = 12,
                            UnidadMedida = "unidad"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Categoria = 0,
                            Nombre = "Cobertor de almohada",
                            StockActual = 80,
                            StockMinimo = 20,
                            UnidadMedida = "unidad"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Categoria = 1,
                            Nombre = "Cubiertos (juego)",
                            StockActual = 100,
                            StockMinimo = 20,
                            UnidadMedida = "juego"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Categoria = 1,
                            Nombre = "Tazas",
                            StockActual = 60,
                            StockMinimo = 15,
                            UnidadMedida = "unidad"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Categoria = 1,
                            Nombre = "Platos",
                            StockActual = 60,
                            StockMinimo = 15,
                            UnidadMedida = "unidad"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Categoria = 1,
                            Nombre = "Huevos",
                            StockActual = 20,
                            StockMinimo = 5,
                            UnidadMedida = "docena"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Categoria = 1,
                            Nombre = "Mantequilla Horeca",
                            StockActual = 15,
                            StockMinimo = 5,
                            UnidadMedida = "unidad"
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Categoria = 1,
                            Nombre = "Mermelada Horeca",
                            StockActual = 15,
                            StockMinimo = 5,
                            UnidadMedida = "unidad"
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            Categoria = 1,
                            Nombre = "Té filtrante",
                            StockActual = 30,
                            StockMinimo = 8,
                            UnidadMedida = "caja"
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            Categoria = 1,
                            Nombre = "Café en sobres",
                            StockActual = 30,
                            StockMinimo = 8,
                            UnidadMedida = "caja"
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            Categoria = 1,
                            Nombre = "Aceite",
                            StockActual = 20,
                            StockMinimo = 5,
                            UnidadMedida = "litro"
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            Categoria = 1,
                            Nombre = "Agua embotellada",
                            StockActual = 100,
                            StockMinimo = 20,
                            UnidadMedida = "unidad"
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            Categoria = 1,
                            Nombre = "Gaseosa (cocina)",
                            StockActual = 60,
                            StockMinimo = 15,
                            UnidadMedida = "unidad"
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            Categoria = 2,
                            Nombre = "Sandalias",
                            StockActual = 40,
                            StockMinimo = 10,
                            UnidadMedida = "par"
                        },
                        new
                        {
                            Id = 17,
                            Activo = true,
                            Categoria = 2,
                            Nombre = "Candados",
                            StockActual = 50,
                            StockMinimo = 10,
                            UnidadMedida = "unidad"
                        },
                        new
                        {
                            Id = 18,
                            Activo = true,
                            Categoria = 2,
                            Nombre = "Toallas",
                            StockActual = 80,
                            StockMinimo = 20,
                            UnidadMedida = "unidad"
                        },
                        new
                        {
                            Id = 19,
                            Activo = true,
                            Categoria = 2,
                            Nombre = "Shorts",
                            StockActual = 40,
                            StockMinimo = 10,
                            UnidadMedida = "unidad"
                        });
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.LogAuditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntidadAfectada")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EntidadId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoAccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LogsAuditoria", (string)null);
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.MovimientoCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Categoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Direccion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrigenCaja")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersonalRelacionado")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MovimientosCaja", (string)null);
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.MovimientoInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<int>("InsumoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InsumoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MovimientosInventario", (string)null);
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.NumeracionComprobante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UltimoCorrelativo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Tipo", "Serie")
                        .IsUnique();

                    b.ToTable("NumeracionesComprobante", (string)null);
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.Penalidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClienteSaunaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EstadiaHotelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteSaunaId");

                    b.HasIndex("EstadiaHotelId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Penalidades", (string)null);
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.ProductoPOS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Categoria")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsAlquilerVenta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioAlquiler")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiereDevolucion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProductosPOS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Categoria = 0,
                            EsAlquilerVenta = true,
                            Icono = "🏖️",
                            Nombre = "Toalla",
                            Precio = 0m,
                            PrecioAlquiler = 5m,
                            PrecioVenta = 20m,
                            RequiereDevolucion = true
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Categoria = 0,
                            EsAlquilerVenta = true,
                            Icono = "🩴",
                            Nombre = "Sandalias",
                            Precio = 0m,
                            PrecioAlquiler = 5m,
                            PrecioVenta = 25m,
                            RequiereDevolucion = true
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Categoria = 1,
                            EsAlquilerVenta = false,
                            Icono = "🧽",
                            Nombre = "Trapo exfoliante",
                            Precio = 8m,
                            PrecioAlquiler = 0m,
                            PrecioVenta = 0m,
                            RequiereDevolucion = false
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Categoria = 1,
                            EsAlquilerVenta = false,
                            Icono = "🥽",
                            Nombre = "Lentes de natación",
                            Precio = 15m,
                            PrecioAlquiler = 0m,
                            PrecioVenta = 0m,
                            RequiereDevolucion = false
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            Categoria = 0,
                            EsAlquilerVenta = true,
                            Icono = "🩳",
                            Nombre = "Shorts",
                            Precio = 0m,
                            PrecioAlquiler = 8m,
                            PrecioVenta = 35m,
                            RequiereDevolucion = true
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Categoria = 2,
                            EsAlquilerVenta = false,
                            Icono = "🥤",
                            Nombre = "Gaseosa",
                            Precio = 5m,
                            PrecioAlquiler = 0m,
                            PrecioVenta = 0m,
                            RequiereDevolucion = false
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Categoria = 2,
                            EsAlquilerVenta = false,
                            Icono = "💧",
                            Nombre = "Agua mineral",
                            Precio = 3m,
                            PrecioAlquiler = 0m,
                            PrecioVenta = 0m,
                            RequiereDevolucion = false
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Categoria = 2,
                            EsAlquilerVenta = false,
                            Icono = "🧃",
                            Nombre = "Rehidratante",
                            Precio = 6m,
                            PrecioAlquiler = 0m,
                            PrecioVenta = 0m,
                            RequiereDevolucion = false
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Categoria = 2,
                            EsAlquilerVenta = false,
                            Icono = "🍹",
                            Nombre = "Jugo natural",
                            Precio = 7m,
                            PrecioAlquiler = 0m,
                            PrecioVenta = 0m,
                            RequiereDevolucion = false
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Categoria = 3,
                            EsAlquilerVenta = false,
                            Icono = "🍡",
                            Nombre = "Paleta",
                            Precio = 4m,
                            PrecioAlquiler = 0m,
                            PrecioVenta = 0m,
                            RequiereDevolucion = false
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Categoria = 3,
                            EsAlquilerVenta = false,
                            Icono = "🍮",
                            Nombre = "Gelatina",
                            Precio = 4m,
                            PrecioAlquiler = 0m,
                            PrecioVenta = 0m,
                            RequiereDevolucion = false
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            Categoria = 3,
                            EsAlquilerVenta = false,
                            Icono = "🍰",
                            Nombre = "Keke",
                            Precio = 6m,
                            PrecioAlquiler = 0m,
                            PrecioVenta = 0m,
                            RequiereDevolucion = false
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            Categoria = 3,
                            EsAlquilerVenta = false,
                            Icono = "🥟",
                            Nombre = "Empanada",
                            Precio = 6m,
                            PrecioAlquiler = 0m,
                            PrecioVenta = 0m,
                            RequiereDevolucion = false
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            Categoria = 3,
                            EsAlquilerVenta = false,
                            Icono = "🥪",
                            Nombre = "Sánguche",
                            Precio = 9m,
                            PrecioAlquiler = 0m,
                            PrecioVenta = 0m,
                            RequiereDevolucion = false
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            Categoria = 3,
                            EsAlquilerVenta = false,
                            Icono = "🥗",
                            Nombre = "Ensalada",
                            Precio = 12m,
                            PrecioAlquiler = 0m,
                            PrecioVenta = 0m,
                            RequiereDevolucion = false
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            Categoria = 5,
                            EsAlquilerVenta = false,
                            Icono = "👔",
                            Nombre = "Planchado (prenda)",
                            Precio = 5m,
                            PrecioAlquiler = 0m,
                            PrecioVenta = 0m,
                            RequiereDevolucion = false
                        },
                        new
                        {
                            Id = 17,
                            Activo = true,
                            Categoria = 5,
                            EsAlquilerVenta = false,
                            Icono = "🧺",
                            Nombre = "Lavandería (kg)",
                            Precio = 10m,
                            PrecioAlquiler = 0m,
                            PrecioVenta = 0m,
                            RequiereDevolucion = false
                        },
                        new
                        {
                            Id = 18,
                            Activo = true,
                            Categoria = 5,
                            EsAlquilerVenta = false,
                            Icono = "🛏️",
                            Nombre = "Frazada adicional",
                            Precio = 15m,
                            PrecioAlquiler = 0m,
                            PrecioVenta = 0m,
                            RequiereDevolucion = false
                        },
                        new
                        {
                            Id = 19,
                            Activo = true,
                            Categoria = 5,
                            EsAlquilerVenta = false,
                            Icono = "🧻",
                            Nombre = "Toalla adicional",
                            Precio = 10m,
                            PrecioAlquiler = 0m,
                            PrecioVenta = 0m,
                            RequiereDevolucion = false
                        });
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.Reclamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BienContratado")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetalleReclamo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentoApoderado")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsMenorDeEdad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MontoReclamado")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreApoderado")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PedidoConsumidor")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RespuestaEstablecimiento")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioRegistroId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioRegistroId");

                    b.ToTable("Reclamos", (string)null);
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.RegistroLimpieza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("HabitacionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsuarioFinId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioInicioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HabitacionId");

                    b.HasIndex("UsuarioFinId");

                    b.HasIndex("UsuarioInicioId");

                    b.ToTable("RegistrosLimpieza", (string)null);
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoFacturacion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EstadiaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("HabitacionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.Property<string>("RUC")
                        .HasColumnType("TEXT");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoComprobante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HabitacionId");

                    b.HasIndex("UsuarioCreacionId");

                    b.ToTable("Reservas", (string)null);
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreCompleto = "Gerencia",
                            PasswordHash = "$2b$11$JucXsFC6/Xlkhh/qvHvjDejcGLdbOjdbfzyCbQEDTMJYxxWIf6Gf2",
                            Rol = 0,
                            Username = "gerencia.1"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreCompleto = "Recepción General",
                            PasswordHash = "$2b$11$JucXsFC6/Xlkhh/qvHvjDejcGLdbOjdbfzyCbQEDTMJYxxWIf6Gf2",
                            Rol = 1,
                            Username = "recepcion"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreCompleto = "Marcelo López",
                            PasswordHash = "$2b$11$JucXsFC6/Xlkhh/qvHvjDejcGLdbOjdbfzyCbQEDTMJYxxWIf6Gf2",
                            Rol = 2,
                            Username = "marcelo.dev"
                        });
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.VentaSauna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClienteSaunaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EstadiaHotelDestinoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MetodoPago")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroComprobante")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteSaunaId");

                    b.HasIndex("EstadiaHotelDestinoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("VentasSauna", (string)null);
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.Acompanante", b =>
                {
                    b.HasOne("JKalixto_System.Domain.Models.Estadia", null)
                        .WithMany("Acompanantes")
                        .HasForeignKey("EstadiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.AcompananteReserva", b =>
                {
                    b.HasOne("JKalixto_System.Domain.Models.Reserva", null)
                        .WithMany("Acompanantes")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.CierreCaja", b =>
                {
                    b.HasOne("JKalixto_System.Domain.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.ClienteSauna", b =>
                {
                    b.HasOne("JKalixto_System.Domain.Models.Estadia", null)
                        .WithMany()
                        .HasForeignKey("EstadiaHotelId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.DetalleVenta", b =>
                {
                    b.HasOne("JKalixto_System.Domain.Models.ProductoPOS", null)
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JKalixto_System.Domain.Models.VentaSauna", null)
                        .WithMany("Detalles")
                        .HasForeignKey("VentaSaunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.Estadia", b =>
                {
                    b.HasOne("JKalixto_System.Domain.Models.Habitacion", "Habitacion")
                        .WithMany()
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JKalixto_System.Domain.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioCheckInId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JKalixto_System.Domain.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioCheckOutId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Habitacion");
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.LogAuditoria", b =>
                {
                    b.HasOne("JKalixto_System.Domain.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.MovimientoCaja", b =>
                {
                    b.HasOne("JKalixto_System.Domain.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.MovimientoInventario", b =>
                {
                    b.HasOne("JKalixto_System.Domain.Models.Insumo", null)
                        .WithMany()
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JKalixto_System.Domain.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.Penalidad", b =>
                {
                    b.HasOne("JKalixto_System.Domain.Models.ClienteSauna", null)
                        .WithMany()
                        .HasForeignKey("ClienteSaunaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JKalixto_System.Domain.Models.Estadia", null)
                        .WithMany()
                        .HasForeignKey("EstadiaHotelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JKalixto_System.Domain.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.Reclamo", b =>
                {
                    b.HasOne("JKalixto_System.Domain.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioRegistroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.RegistroLimpieza", b =>
                {
                    b.HasOne("JKalixto_System.Domain.Models.Habitacion", null)
                        .WithMany()
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JKalixto_System.Domain.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioFinId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JKalixto_System.Domain.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioInicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.Reserva", b =>
                {
                    b.HasOne("JKalixto_System.Domain.Models.Habitacion", "Habitacion")
                        .WithMany()
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JKalixto_System.Domain.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Habitacion");
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.VentaSauna", b =>
                {
                    b.HasOne("JKalixto_System.Domain.Models.ClienteSauna", null)
                        .WithMany()
                        .HasForeignKey("ClienteSaunaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JKalixto_System.Domain.Models.Estadia", null)
                        .WithMany()
                        .HasForeignKey("EstadiaHotelDestinoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JKalixto_System.Domain.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.Estadia", b =>
                {
                    b.Navigation("Acompanantes");
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.Reserva", b =>
                {
                    b.Navigation("Acompanantes");
                });

            modelBuilder.Entity("JKalixto_System.Domain.Models.VentaSauna", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
